### ISSUE TITLE
REQUEST: Task list of important things to add at this repo.

### ISSUE THREAD

**Issue by icecodder** [discord-bugcenter/BC_HelperBot#20]
I have a lot of changes to add at this repo. See this list :

- [x] Add CONTRIBUTING file to explain how to contribute, how to name our commit, our pr, etc. (write only in english!)
- [ ] Add GitHub Actions scripts for CI/CD deployment.
- [x] Add description to this repo, for explain what is it.
- [x] Stop to switch between french & english (in commits, pr, issue, etc) for more understanding. PLEASE CHOOSE ONLY ONE LANGUAGE!
- [x] Add code of conduct
- [x] Add issue templates
- [x] Add pr templates

See this pictures :
![image](https://user-images.githubusercontent.com/47574874/107847809-06956f00-6def-11eb-9bbd-c5f01d0f053a.png)

Here is already a good list of things to do, I will add more things in the future.

**Comment by n1c00o** [comment]
As I said a few weeks ago on the server, English is the main language for programming stuff and we should not use French, even if the majority of our community is still french, moving to English is crucial in Open Source

**Comment by n1c00o** [comment]
I will do the README, the CODE_OF_CONDUCT and the CONTRIBUTING files

**Comment by n1c00o** [comment]
Issue templates are not needed but I can write some

**Comment by icecodder** [comment]
> As I said a few weeks ago on the server, English is the main language for programming stuff and we should not use French, even if the majority of our community is still french, moving to English is crucial in Open Source

Yes, Open Source in only in ENGLISH! We should not use French. Bug Center community need to speak English for Contributing.

**Comment by n1c00o** [comment]
Related to #23 #22.

I will see later to implements some workflows, using Actions or smth else.
